---
- name: install docker-compose
  become: true
  get_url:
    url: 'https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Linux-x86_64'
    dest: '/usr/local/bin/docker-compose'
    force: true
    mode: '555'
  tags: docker-compose
